Fix for ConversionError when specifying timelimits
Specifying timelimits as a tuple of strings can raise:
```AttributeError: 'numpy.str_' object has no attribute 'toordinal'```
and ultimately:
```ConversionError: Failed to convert value(s) to axis units```
which is traced back to
`ax[-1].set_xlim(timelimits)` in `_format_time_axis`.


Tested with matplotlib 3.1.3 (conda-forge)